export const USERS_ACTION_TYPE = {
  USER_LIST_UPLOAD_PENDING: "USERS_ACTION_TYPE.USER_LIST_UPLOAD_PENDING",
  USER_LIST_UPLOAD_SUCCESS: "USERS_ACTION_TYPE.USER_LIST_UPLOAD_SUCCESS",
  USER_LIST_UPLOAD_ERROR: "USERS_ACTION_TYPE.USER_LIST_UPLOAD_ERROR",
  USER_DATA: "USERS_ACTION_TYPE.USER_DATA",
}
