export const THEME_COLOR = {
  PRIMARY: '#fff',
  INPUT_ERROR: 'red',
  TEXT_SECONDARY: '#707070',
  FORM_ERROR_TEXT: '#590000',
  FORM_ERROR_BACKGROUND: '#FFE6E6',
  
  INPUT: {
    BACKGROUND_COLOR: '#f3f3f3'
  },
  BUTTON: {
    PRIMARY: {
      BACKGROUND_COLOR: '#2BA7ED',
      COLOR: '#FFFFFF'
    }
  }
};
