import { SIGNUP_FORM_FIELD_KEY } from '../signup/frame/signup-form'

export const SIGNUP_FIELD_NAME = {
  LOGIN: 'login', 
  PASSOWORD: 'password',
}

export const SIGNUP_FORM_FIELD_NAME = {
  [SIGNUP_FORM_FIELD_KEY.LOGIN]: SIGNUP_FIELD_NAME.LOGIN,
  [SIGNUP_FORM_FIELD_KEY.PASSOWORD]: SIGNUP_FIELD_NAME.PASSOWORD,
}

export const SIGNUP_ACTION_TYPE = {
  SIGNUP_FORM_UPLOAD_PENDING: "SIGNUP_ACTION_TYPE.SIGNUP_FORM_UPLOAD_PENDING",
  SIGNUP_FORM_UPLOAD_SUCCESS: "SIGNUP_ACTION_TYPE.SIGNUP_FORM_UPLOAD_SUCCESS",
  SIGNUP_FORM_UPLOAD_ERROR: "SIGNUP_ACTION_TYPE.SIGNUP_FORM_UPLOAD_ERROR",
  SIGNUP_FORM_UPLOAD_RESET: "SIGNUP_ACTION_TYPE.SIGNUP_FORM_UPLOAD_RESET",
}

export const SIGNUP_DATA_NAME = {
  LOGIN: 'login',
  PASSWORD: 'password',
}